#项目配置
app:
  name: dogo
  mode: dev
  port: 8080
  version: v0.0.1
#日志配置
log:
  level: debug
  filename: dogo.log
  max_size: 200
  max_age: 30
  max_backup: 7
#数据库连接设置
datasource:
  driver_name: mysql
  host: 127.0.0.1
  port: 3306
  database: net_group
  username: root
  password: root
  charset: utf8
  loc: Asia/Shanghai
  max_open_conns: 200
  max_idle_conns: 50

#redis设置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100
